---
openapi: 3.0.2
info:
  title: DNA Synthesis API
  version: "1.0"
servers:
  - url: http://localhost:3001/

paths:
  /machines:
    get:
      summary: Return a list of all machines; optionally, filtered by status
      parameters:
        - in: query
          name: status
          schema:
            $ref: "#/components/schemas/MachineStatus"
          description: Return only machines with the given status
      responses:
        "200":
          description: A JSON array of machines, applying any query filter
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Machine"
        "400":
          description: Returns an error if given a `status` query filter with an invalid status value
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Invalid query parameter "status"
  /machines/{machineId}:
    get:
      summary: "Returns the description and status of the machine identified by its ID"
      parameters:
        - in: path
          name: machineId
          schema:
            type: integer
          required: true
          description: ID of the machine to get
      responses:
        "200":
          description: The description and status of the machine
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Machine"
        "404":
          description: Returns an error if no machine exists with `machineId`
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Machine not found

  /models:
    get:
      summary: "Returns a list of all machine models"
      parameters: []
      responses:
        "200":
          description: a JSON array of models"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Model"
  /models/{modelId}:
    get:
      summary: "Returns the description of the model identified by its ID"
      parameters:
        - in: path
          name: modelId
          schema:
            type: string
          required: true
          description: ID of the model to get
      responses:
        "200":
          description: The description of the model
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Model"
        "404":
          description: Returns an error if no model exists with `machineId`
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Model not found
components:
  schemas:
    Machine:
      type: object
      properties:
        id:
          type: integer
          description: The machine id
        model:
          type: string
          description: The machine model
        location:
          type: string
          description: The machine location
        status:
          $ref: "#/components/schemas/MachineStatus"
        order:
          type: integer
          description: The order id currently assigned to the machine. Only present if there's an assigned order to the machine (i.e. `status != IDLE`)
        synthesis:
          type: object
          description: Synthesis information. Only present if there's an assigned order to the machine (i.e. `status != IDLE`)
          properties:
            totalCycles:
              type: integer
              description: The total number of cycles needed to synthetize ALL oligos and fulfill the current order
            completedCycles:
              type: integer
              description: |
                The number of completed cycles.
                * Is always less than or equal than `totalCycles`
                * Should be `0` when `status == IDLE_ASSIGNED_ORDER`
                * Should equal to `totalCycles` when `status == WAITING_FOR_DISPATCH`
            currentStep:
              type: string
              enum:
                - ELONGATION
                - DEPROTECTION
                - WASH
              description: |
                The machine's current step within its operational cycle. A cycle consists of 3 steps : ELONGATION -> DEPROTECTION -> WASH
                * It is present only when machine's `status == SYNTHETIZING`
        wells:
          type: array
          description: A description of each well in the machine
          items:
            type: object
            properties:
              id:
                type: integer
                description: the well unique id within the machine
              row:
                type: integer
                description: the well row number. row numbers start with 0
              col:
                type: integer
                description: the well column number. column numbers start with 0
              status:
                type: string
                enum:
                  - IDLE
                  - IDLE_ASSIGNED_OLIGO
                  - SYNTHETIZING_OLIGO
                  - COMPLETED_OLIGO
                description: |
                  This field represents the current well state. It can take one of the following values:

                  - IDLE: takes this value if and only if `status(machine) == IDLE`
                  - IDLE_ASSIGNED_OLIGO: takes this value if and only if `status(machine) == IDLE_ASSIGNED_ORDER`
                  - SYNTHETIZING_OLIGO: takes this value if `status(machine) == SYNTHETIZING AND length(oligo) < completedCycles`
                  - COMPLETED_OLIGO: takes this value if `status(machine) == WAITING_FOR_DISPATCH OR (`status(machine) == SYNTHETIZING AND synthetizedNucleotideCount < totalCycles)`
              oligo:
                type: string
                pattern: ^[ATCG]+$
                description: the oligonucleotide that is synthetized in this well. Only present if there's an assigned order to the machine (i.e. `status != IDLE`)
              totalCycles:
                type: integer
                description: |
                  The total number of cycles needed to synthetize the assigned oligo.
                  * Only present if there's an assigned order to the machine (i.e. `status != IDLE`)
                  * It is always equal to `oligo`'s length
              synthetizedNucleotideCount:
                type: integer
                description: |
                  The current nucleotide length, or the number of completed cycles.
                  * Only present if there's an assigned order to the machine (i.e. `status != IDLE`)
                  * It is always less than or equal than `totalCycles`
                  * `synthetizedNucleotideCount == totalCycles` if and only if `status == COMPLETED_OLIGO`
    Model:
      type: object
      properties:
        id:
          type: string
          description: The unique model id and name
        wellArraySize:
          type: array
          description: "an array of 2 values : [number of rows, number of columns] of the model's well array."
          items:
            type: integer
          minItems: 2
          maxItems: 2
    MachineStatus:
      type: string
      enum:
        - IDLE
        - IDLE_ASSIGNED_ORDER
        - SYNTHETIZING
        - WAITING_FOR_DISPATCH
      description: |
        This field represents the current machine state. It can take one of the following values:

        - IDLE: The machine is idle and not processing any orders.
        - IDLE_ASSIGNED_ORDER: The machine has an assigned order, but did not start synthesis yet.
        - SYNTHETIZING: The machine is currently synthesizing an order.
        - WAITING_FOR_DISPATCH: The order synthesis is completed and it's waiting for the oligos to be dispatched.
